### ISSUE TITLE
TaskbarItemInfo stuck on on 'paused' after clicking 'close' button on dialog "Class generator - EF key code".

### ISSUE THREAD

**Issue by FelixLeander** [InvaderZim85/MsSqlToolBelt#173]
As mentioned in the title, this gets stuck:
![image](https://github.com/InvaderZim85/MsSqlToolBelt/assets/55660647/e6fc4769-ce28-4b21-8dc4-84b0f7955a49)

## Steps to reproduce:
1. start the program.
2. connect to a Server and select a Database.
3. click on the tab "Class generator".
4. on the left pane, select a table.
5. on the right pane, in the middle, click the button "SHOW EF KEY CODE" (on the following screenshot '1').
6. In the new window, click the button "CLOSE" (on the following screenshot 'B').

## Extra Info
On the following screenshot, when closing with the X menu item ('A'), then it doesn't get stuck.
![msqSqlToolBelt](https://github.com/InvaderZim85/MsSqlToolBelt/assets/55660647/a4c614a6-4873-409f-9d3c-dcff2d4e36db)

**Comment by InvaderZim85** [comment]
Will be fixed in https://github.com/InvaderZim85/MsSqlToolBelt/pull/174

**Comment by InvaderZim85** [comment]
Bug has been fixed in the new version.

New Version: [v24.181.0.996](https://github.com/InvaderZim85/MsSqlToolBelt/releases/tag/v24.181.0.996)
